[package]
name = "math_crypto_baby-step_giant-step"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flame = "0.2.2"
flamescope = "0.1.2"
num = "0.4.0"
num-iter = "0.1.43"
tqdm = "0.5.0"
